/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_commander_window (void);
GtkWidget* create_about_window (void);
GtkWidget* create_format7_window (void);
GtkWidget* create_no_handle_window (void);
GtkWidget* create_no_camera_window (void);
GtkWidget* create_get_filename_dialog (void);
GtkWidget* create_preferences_window (void);
GtkWidget* create_help_window (void);
