/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_commander_window (void);
GtkWidget* create_porthole_window (void);
GtkWidget* create_color_window (void);
GtkWidget* create_aperture_window (void);
GtkWidget* create_status_window (void);
GtkWidget* create_capture_window (void);
GtkWidget* create_temp_window (void);
GtkWidget* create_about_window (void);
GtkWidget* create_format7_window (void);
GtkWidget* create_no_handle_window (void);
GtkWidget* create_no_camera_window (void);
GtkWidget* create_format6_window (void);
GtkWidget* create_save_single_dialog (void);
GtkWidget* create_capture_multi_dialog (void);
GtkWidget* create_preferences_window (void);
